- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Update and upgrade apt packages
      apt:
       upgrade: yes
       update_cache: yes
       cache_valid_time: 86400 #One day

    - name: install JDK 11
      apt:
        name: openjdk-11-jdk
        state: present

    - name: add tomcat group
      group:
        name: tomcat

    - name: add tomcat user
      user:
        name: tomcat
        group: tomcat
        home: /user/share/tomcat
        createhome: no

    - name: create /opt/tomcat directory
      file:
        path: /opt/tomcat
        state: directory
        mode: 0755

    - name: download & unarchive
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.76/bin/apache-tomcat-9.0.76.tar.gz
        dest: /opt/tomcat
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Change ownership
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: make tomcat.service
      file:
          path: /etc/systemd/system/tomcat.service
          state:  touch
    - name: edit tomcat.service
      blockinfile:
          dest: /etc/systemd/system/tomcat.service
          insertafter:
          block: |
            [Unit]
            Description=Apache Tomcat Web Application Container
            After=network.target

            [Service]
            Type=forking

            Environment=JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64
            Environment=CATALINA_PID=/opt/tomcat/temp/tomcat.pid
            Environment=CATALINA_HOME=/opt/tomcat
            Environment=CATALINA_BASE=/opt/tomcat
            Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
            Environment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'
            ExecStart=/opt/tomcat/bin/startup.sh
            ExecStop=/opt/tomcat/bin/shutdown.sh

            User=tomcat
            Group=tomcat
            UMask=0007
            RestartSec=10
            Restart=always

            [Install]
            WantedBy=multi-user.target

    - name: Start and enable Tomcat service
      systemd:
        name: tomcat
        state: started
        enabled: true
        daemon_reload: true

    - name: add roles
      lineinfile:
        path: /opt/tomcat/conf/tomcat-users.xml
        insertbefore: </tomcat-users>
        line: "{{item}}"
      with_items:
        - <role rolename="admin-gui"/>
        - <role rolename="manager-gui"/>
        - <user username="admin" password="admin" roles="admin-gui,manager-gui"/>

    - name: enable manager app
      lineinfile:
        path: /opt/tomcat/webapps/manager/META-INF/context.xml
        state: absent
        regexp: "{{item}}"
      with_items:
        - <Valve className="org.apache.catalina.valves.RemoteAddrValve"
        - allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1" />
    - name: restart tomcat
      service: name=tomcat state=restarted
    - name: download artifact
      get_url:
        url: githuburl/target/*.war
        dest: /tmp
    - name: copy artifact
      copy:
        src: /tmp/add.war
        dest: /opt/tomcat/webapps/add.war
        owner: tomcat
        group: tomcat
        remote_src: yes